name: CD - Build & Release

on:
  workflow_dispatch: # permet de tester manuellement
  workflow_run:
    workflows: ["CI"] # DOIT correspondre exactement au name de ton ci.yml
    types: [completed]
    branches: [main]

permissions:
  contents: write

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows_build:
    name: Build Windows EXE
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Build EXE with Compose
        run: .\gradlew.bat packageExe --no-daemon --stacktrace

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exe-build
          path: |
            build/compose/binaries/main/exe/*.exe
            build/compose/binaries/main/msi/*.msi

  release:
    name: Create GitHub Release
    needs: windows_build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: exe-build
          path: dist

      - name: Show files
        run: ls -R dist || true

      - name: Create Release + Upload EXE
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            ✅ Build automatique depuis commit :
            ${{ github.event.workflow_run.head_sha }}
          files: |
            dist/**/*.exe
            dist/**/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}